{{- if and .Values.nats.jwt .Values.nats.secondJwt -}}
apiVersion: v1
kind: Secret
metadata:
  name: kubiya-runner-nats-creds-runner
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubiya-runner-common.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
type: Opaque
data:
  nats.creds: {{ .Values.nats.jwt | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: kubiya-runner-nats-creds-customer
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubiya-runner-common.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
type: Opaque
data:
  nats.creds: {{ .Values.nats.secondJwt | quote }}
{{- end }}
