{{- if and .Values.registryTls.crt .Values.registryTls.key -}}
apiVersion: v1
kind: Secret
metadata:
  name: registry-tls-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubiya-runner-common.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.registryTls.crt | quote }}
  tls.key: {{ .Values.registryTls.key | quote }}
{{- end }}
