{{- if eq .Values.engine.kind "StatefulSet" -}}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "dagger.fullname" . }}-engine
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dagger.labels" . | nindent 4 }}
spec:
  # DO NOT RUN MORE THAN 1 REPLICA IF USING HOSTPATH.
  # Only one (1) Engine is able to hold the lock, other replicas will not be able to start.
  # If using persistent volumes, this is not an issue. Use more than 1 replica if you know that you need it.
  replicas: 1
  podManagementPolicy: {{ .Values.engine.statefulSet.podManagementPolicy }}
  selector:
    matchLabels:
      name: {{ include "dagger.fullname" . }}-engine
  {{- if and .Values.engine.statefulSet.persistentVolumeClaim.enabled .Values.engine.statefulSet.persistentVolumeClaimRetentionPolicy }}
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: {{ .Values.engine.statefulSet.persistentVolumeClaimRetentionPolicy.whenDeleted }}
    whenScaled: {{ .Values.engine.statefulSet.persistentVolumeClaimRetentionPolicy.whenScaled }}
  {{- end }}
  template:
    metadata:
      {{- if (or .Values.engine.config .Values.magicache.enabled) }}
      annotations:
        {{- if .Values.engine.config }}
        checksum/config: {{ include (print $.Template.BasePath "/engine-config.yaml") . | sha256sum }}
        {{- end }}
        {{- if .Values.magicache.enabled }}
        checksum/secret: {{ include (print $.Template.BasePath "/magicache-secret.yaml") . | sha256sum }}
        {{- end }}
      {{- end }}
      labels:
        name: {{ include "dagger.fullname" . }}-engine
        {{- include "dagger.labels" . | nindent 8 }}
    spec:
      {{- with .Values.engine.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.engine.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.engine.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.engine.securityContext | nindent 8 }}
      serviceAccountName: {{ include "dagger.serviceAccountName" . }}
      {{- if .Values.engine.priorityClassName }}
      priorityClassName: {{ .Values.engine.priorityClassName }}
      {{- end }}
      containers:
        - name: dagger-engine
          image: {{ if .Values.engine.image.ref }}{{ .Values.engine.image.ref }}{{ else }}registry.dagger.io/engine:v{{ .Chart.Version }}{{ end }}
          imagePullPolicy: {{ .Values.engine.image.pullPolicy }}
          {{- if .Values.engine.args }}
          args:
            {{- toYaml .Values.engine.args | nindent 12 }}
          {{- end }}
          {{- if .Values.magicache.enabled }}
          env:
          - name: _EXPERIMENTAL_DAGGER_CACHESERVICE_URL
            value: {{ required "A magicache url is required" .Values.magicache.url }}
          envFrom:
          - secretRef:
              {{- if .Values.magicache.secretName }}
              name: {{ .Values.magicache.secretName }}
              {{- else }}
              name: {{ include "dagger.fullname" . }}-magicache-token
              {{- end }}
          {{- end }}
          securityContext:
            {{- toYaml .Values.engine.containerSecurityContext | nindent 12 }}
          resources: {{- toYaml .Values.engine.resources | nindent 12 }}
          {{- if .Values.engine.lifecycle }}
          lifecycle:
            {{- if .Values.engine.lifecycle.preStop }}
            preStop:
              {{- toYaml .Values.engine.lifecycle.preStop | nindent 14 }}
            {{- end }}
          {{- end }}
          readinessProbe:
            {{- toYaml .Values.engine.readinessProbe | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /var/lib/dagger{{- if .Values.volumeMountsPostfix }}-{{- .Values.volumeMountsPostfix }}{{- end }}
            {{- if .Values.engine.hostPath.runVolume.enabled }}
            - name: run
              mountPath: /run/dagger{{- if .Values.volumeMountsPostfix }}-{{- .Values.volumeMountsPostfix }}{{- end }}
            {{- end }}
            {{- if .Values.engine.config }}
            - name: dagger-engine-config
              mountPath: /etc/dagger/engine.toml
              subPath: engine.toml
            {{- end }}
      terminationGracePeriodSeconds: {{ .Values.engine.terminationGracePeriodSeconds }}
      volumes:
        {{- if .Values.engine.hostPath.runVolume.enabled }}
        - name: run
          hostPath:
            path: /run/dagger
        {{- end }}
        {{- if .Values.engine.config }}
        - name: dagger-engine-config
          configMap:
            name: {{ include "dagger.fullname" . }}-engine-config
            items:
              - key: engine.toml
                path: engine.toml
        {{- end }}
  {{- if .Values.engine.statefulSet.persistentVolumeClaim.enabled }}
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      {{- with .Values.engine.statefulSet.persistentVolumeClaim.storageClassName }}
      storageClassName: {{ . }}
      {{- end }}
      accessModes:
        {{- toYaml .Values.engine.statefulSet.persistentVolumeClaim.accessModes | nindent 8 }}
      resources:
        {{- toYaml .Values.engine.statefulSet.persistentVolumeClaim.resources | nindent 8 }}
  {{- end }}
{{- end }} 