---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "dagger.fullname" . }}-engine
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dagger.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      name: {{ include "dagger.fullname" . }}-engine
  template:
    metadata:
      {{- if (or .Values.engine.config .Values.magicache.enabled) }}
      annotations:
        {{- if .Values.engine.config }}
        checksum/config: {{ include (print $.Template.BasePath "/engine-config.yaml") . | sha256sum }}
        {{- end }}
        {{- if .Values.magicache.enabled }}
        checksum/secret: {{ include (print $.Template.BasePath "/magicache-secret.yaml") . | sha256sum }}
        {{- end }}
      {{- end }}
      labels:
        name: {{ include "dagger.fullname" . }}-engine
        {{- include "dagger.labels" . | nindent 8 }}
    spec:
      {{- with .Values.engine.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.engine.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.engine.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.engine.securityContext | nindent 8 }}
      serviceAccountName: {{ include "dagger.serviceAccountName" . }}
      {{- if .Values.engine.priorityClassName }}
      priorityClassName: {{ .Values.engine.priorityClassName }}
      {{- end }}
      containers:
        - name: dagger-engine
          image: {{ if .Values.engine.image.ref }}{{ .Values.engine.image.ref }}{{ else }}registry.dagger.io/engine:v{{ .Chart.Version }}{{ end }}
          imagePullPolicy: {{ .Values.engine.image.pullPolicy }}
          {{- if .Values.engine.args }}
          args:
            {{- toYaml .Values.engine.args | nindent 12 }}
          {{- end }}
          {{- if .Values.magicache.enabled }}
          env:
          - name: _EXPERIMENTAL_DAGGER_CACHESERVICE_URL
            value: {{ required "A magicache url is required" .Values.magicache.url }}
          envFrom:
          - secretRef:
              {{- if .Values.magicache.secretName }}
              name: {{ .Values.magicache.secretName }}
              {{- else }}
              name: {{ include "dagger.fullname" . }}-magicache-token
              {{- end }}
          {{- end }}
          securityContext:
            {{- toYaml .Values.engine.containerSecurityContext | nindent 12 }}
          resources: {{- toYaml .Values.engine.resources | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.engine.readinessProbe | nindent 12 }}
          volumeMounts:
            - name: varlibdagger
              mountPath: /var/lib/dagger{{- if .Values.volumeMountsPostfix }}-{{- .Values.volumeMountsPostfix }}{{- end }}
              # Volume prefixes below are following mountPath name same as they were existed in initial pre-chart version of kubiya_runner template file and found working.
              # TODO: review why we are not using hostPath name postfix instead?
            - name: varrundagger
              mountPath: /var/run/buildkit{{- if .Values.volumeMountsPostfix }}-{{- .Values.volumeMountsPostfix }}{{- end }}
            {{- if .Values.engine.config }}
            - name: dagger-engine-config
              mountPath: /etc/dagger/engine.toml
              subPath: engine.toml
            {{- end }}
      terminationGracePeriodSeconds: {{ .Values.engine.terminationGracePeriodSeconds }}
      volumes:
        - name: varlibdagger
          hostPath:
            path: /var/lib/dagger
        - name: varrundagger
          hostPath:
            path: /var/run/dagger
        {{- if .Values.engine.config }}
        - name: dagger-engine-config
          configMap:
            name: {{ include "dagger.fullname" . }}-engine-config
            items:
              - key: engine.toml
                path: engine.toml
        {{- end }}
