{{- if and .Values.otelcollector.prometheusExporter.enabled .Values.otelcollector.prometheusExporter.managedPrometheusAuth.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: kubiya-runner-azure-prometheus-auth
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubiya-runner-common.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
type: Opaque
data:
  token: {{ required "Azure Managed Prometheus auth token is required when managedPrometheusAuth is enabled" .Values.otelcollector.prometheusExporter.managedPrometheusAuth.token | b64enc | quote }}
{{- end }} 
