{{- if .Values.otelcollector.customRole.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "kubiya-runner.name" . }}-otel-collector
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "otel-collector-extras.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["events", "pods", "pods/status", "replicationcontrollers", "replicationcontrollers/status", "resourcequotas", "services", "endpoints"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["daemonsets", "deployments", "replicasets", "statefulsets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["extensions"]
    resources: ["daemonsets", "deployments", "replicasets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["batch"]
    resources: ["jobs", "cronjobs"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["autoscaling"]
    resources: ["horizontalpodautoscalers"]
    verbs: ["get", "list", "watch"]
  {{- if .Values.otelcollector.customRole.enableDebugRoles}}
  {{ toYaml .Values.otelcollector.customRole.enableDebugRoles | nindent 2 -}}
  {{- end }}
{{- end }}
