{{- if .Values.otelcollectorCustomRole }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "kubiya-runner.name" . }}-otel-collector-binding
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "otel-collector-extras.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.otelcollector.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "kubiya-runner.name" . }}-otel-collector
{{- end }}
