{{- if .Values.otelCollectorCustomRole }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "kubiya-runner.name" . }}-otel-collector
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "otel-collector-extras.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["services", "endpoints", "pods", "events"]
    verbs: ["list", "watch"]
  - apiGroups: ["apps"]
    resources: ["replicasets"]
    verbs: ["list", "watch"]
{{- end }}
