{{- if .Values.otelCollectorCustomRole }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "kubiya-runner.name" . }}-otel-collector-binding
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "otel-collector-extras.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.opentelemetryCollector.serviceAccount.name }}
roleRef:
  kind: Role
  name: {{ include "kubiya-runner.name" . }}-otel-collector
  apiGroup: rbac.authorization.k8s.io
{{- end }}
