{{- if and .Values.api.enabled .Values.api.ingress.enabled -}}
{{- $fullName := printf "%s-api" (include "temporal-worker.fullname" .) -}}
{{- $svcPort := .Values.api.service.port -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "temporal-worker.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
  {{- with .Values.api.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.api.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  tls:
    - hosts:
        - {{ .Values.api.ingress.host | quote }}
      secretName: {{ .Values.api.ingress.tlsSecretName | default (printf "%s-tls" $fullName) }}
  rules:
    - host: {{ .Values.api.ingress.host | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
{{- end }}
