{
 "title": "Customer Runners / Runner Health Overview",
 "tags": [
  "kubernetes",
  "health",
  "metrics",
  "customer_runner"
 ],
 "time": { "from": "now-3h", "to": "now-1m" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "organization",
    "query": {
     "query": "label_values(up{kubiya_type=\"customers-runners\"},organization)"
    }
   },
   {
    "name": "runner",
    "query": {
     "query": "label_values(up{kubiya_type=\"customers-runners\", organization=~\"$organization\"},runner)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(up{kubiya_type=\"customers-runners\", organization=~\"$organization\",runner=\"$runner\"},namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Components Pods Ready",
   "type": "state-timeline",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "(\n  sum by (label_app_kubernetes_io_kubiya_runner_component) (\n    kube_pod_status_ready{namespace=\"$namespace\", runner=\"$runner\", condition=\"true\"}\n    * on (pod) group_left(label_app_kubernetes_io_kubiya_runner_component) \n    (\n      kube_pod_labels{namespace=\"$namespace\", runner=\"$runner\"}\n      and on (pod) kube_pod_labels{label_app_kubernetes_io_kubiya_runner_component!=\"\"}\n    )\n  )\n) \n/ \n(\n  count by (label_app_kubernetes_io_kubiya_runner_component) (\n    kube_pod_labels{namespace=\"$namespace\", runner=\"$runner\", label_app_kubernetes_io_kubiya_runner_component!=\"\"}\n  )\n)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Component Pod’s Containers Restarts [per 5m]",
   "type": "state-timeline",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (label_app_kubernetes_io_kubiya_runner_component) (\n  rate(kube_pod_container_status_restarts_total{\n    namespace=\"$namespace\",\n    runner=\"$runner\"\n  }[5m])\n  * on(pod) group_left(label_app_kubernetes_io_kubiya_runner_component)\n  kube_pod_labels{\n    namespace=\"$namespace\",\n    runner=\"$runner\",\n    label_app_kubernetes_io_kubiya_runner_component!=\"\"\n  }\n) * 300 # Multiply by 300 (seconds in 5m) to show actual restart count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Services Health Endpoint Probe [per 5m]",
   "type": "state-timeline",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "label_replace(\n  (avg_over_time(probe_success{\n    namespace=\"$namespace\",\n    runner=\"$runner\",\n    exporter=\"blackbox-exporter\"\n  }[5m]) == 1) * 1,\n  \"state\", \"Healthy\", \"\", \"\"\n) or label_replace(\n  (avg_over_time(probe_success{\n    namespace=\"$namespace\",\n    runner=\"$runner\",\n    exporter=\"blackbox-exporter\"\n  }[5m]) == 0) * 1,\n  \"state\", \"Critical\", \"\", \"\"\n)",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "HTTP Requests Success",
   "type": "state-timeline",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (\n  sum(\n    rate(\n      response_status{\n        status=~\"2..\",\n        runner=\"$runner\",\n        app=\"tool-manager\",\n        namespace=\"$namespace\",\n        organization=\"$organization\"\n      }[5m]\n    )\n  )\n  /\n  sum(\n    rate(\n      http_requests_total{\n        runner=\"$runner\",\n        app=\"tool-manager\",\n        namespace=\"$namespace\",\n        organization=\"$organization\"\n      }[5m]\n    )\n  )\n)",
     "legendFormat": "agent-manager"
    },
    {
     "expr": "100 * (\n  sum(\n    rate(\n      agent_manager_http_requests_total{\n        status=~\"2..\",\n        runner=\"$runner\",\n        namespace=\"$namespace\",\n        organization=\"$organization\"\n      }[5m]\n    )\n  )\n  /\n  sum(\n    rate(\n      agent_manager_http_requests_total{\n        runner=\"$runner\",\n        namespace=\"$namespace\",\n        organization=\"$organization\"\n      }[5m]\n    )\n  )\n)",
     "legendFormat": "agent-manager"
    }
   ]
  },
  { "title": "Helm Chart Versions Installed", "gridPos": { "h": 4, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Components Versions",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "kube_pod_container_info{namespace=~\"$namespace\", runner=\"$runner\", organization=\"$organization\", kubiya_type=\"customers-runners\"}",
     "legendFormat": "{{container}}"
    }
   ]
  }
 ]
}