{
 "title": "Customer Runners / Component Exporter / Agent Manager",
 "tags": [
  " customer_runner",
  "agent_manager",
  "metrics",
  "runners"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "organization",
    "query": {
     "query": "label_values(up{kubiya_type=\"customers-runners\"},organization)"
    }
   },
   {
    "name": "runner",
    "query": {
     "query": "label_values(up{kubiya_type=\"customers-runners\", organization=~\"$organization\"},runner)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(up{kubiya_type=\"customers-runners\", organization=~\"$organization\",runner=\"$runner\"},namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(agent_manager_http_requests_total{namespace=\"$namespace\", runner=\"$runner\",  organization=\"$organization\"})"
    }
   ]
  },
  {
   "title": "Requests Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "agent_manager_http_requests_total{namespace=\"$namespace\", runner=\"$runner\",  organization=\"$organization\"}",
     "legendFormat": "{{method}} {{handler}}"
    }
   ]
  },
  {
   "title": "Requests Average Duration",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "agent_manager_http_request_duration_seconds_sum{namespace=\"$namespace\", runner=\"$runner\",  organization=\"$organization\"} / agent_manager_http_request_duration_seconds_sum{namespace=\"$namespace\", runner=\"$runner\",  organization=\"$organization\"}",
     "legendFormat": "{{method}} {{handler}}"
    }
   ]
  },
  {
   "title": "Tool Run Failure Exceptions",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (runner) (rate(agent_manager_tool_run_failure_counter_total{namespace=\"$namespace\", runner=\"$runner\",  organization=\"$organization\"}[24h]))"
    }
   ]
  },
  {
   "title": "Percent of 2xx Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(handler) (agent_manager_http_requests_total{namespace=\"$namespace\", runner=\"$runner\", organization=\"$organization\", status=~\"2xx\"}) / sum by(handler) (agent_manager_http_requests_total{namespace=\"$namespace\", runner=\"$runner\",  organization=\"$organization\"})",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Percent of 5xx Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(handler) (agent_manager_http_requests_total{namespace=\"$namespace\", runner=\"$runner\", organization=\"$organization\", status=~\"5xx\"}) / sum by(handler) (agent_manager_http_requests_total{namespace=\"$namespace\", runner=\"$runner\",  organization=\"$organization\"})",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "PR 99 Requests Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(agent_manager_http_request_duration_seconds_bucket{namespace=\"$namespace\", runner=\"$runner\",  organization=\"$organization\"}[$__rate_interval])) by (handler, le))",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Request Per Sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(agent_manager_http_requests_total{namespace=\"$namespace\", runner=\"$runner\",  organization=\"$organization\"}[$__rate_interval])",
     "legendFormat": "{{handler}}"
    }
   ]
  }
 ]
}