apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "kubiya-runner.name" . }}-operator
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubiya-operator.labels" . | nindent 4 }}
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
{{- if .Values.kubiyaOperator.fullAccess }}
  - apiGroups: [ "*" ]
    resources: [ "*" ]
    verbs: [ "*" ]
{{- end }}
