apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "kubiya-runner.name" . }}-operator
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubiya-operator.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["pods", "services"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "update", "patch"]
# TODO: Original full access role. Remove if tested ok with less privileges above.
#   - apiGroups: [ "*" ]
#     resources: [ "*" ]
#     verbs: [ "*" ]  
