{{- if .Values.kubiyaOperator.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubiya-runner.serviceAccountName.operator" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubiya-runner-common.labels" . | nindent 4 }}
    app.kubernetes.io/kubiya-runner-component: operator
automountServiceAccountToken: {{ .Values.kubiyaOperator.serviceAccount.automountServiceAccountToken }}
{{- end }}
