{{- if .Values.kubiyaOperator.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubiya-runner.serviceAccountName.operator" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubiya-operator.labels" . | indent 4 }}
  automountServiceAccountToken: {{ .Values.kubiyaOperator.serviceAccount.automountServiceAccountToken }}
{{- end }}
