{{- if .Values.workflowEngine.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubiya-runner.serviceAccountName.workflowEngine" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "workflow-engine.labels" . | nindent 4 }}
  {{- with .Values.workflowEngine.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }} 