apiVersion: v1
kind: Service
metadata:
  name: workflow-engine
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "workflow-engine.labels" . | indent 4 }}
spec:
  selector:
    {{- include "workflow-engine.selectorLabels" . | indent 4 }}
  ports:
    - name: http
      port: {{ .Values.workflowEngine.service.port }}
      targetPort: {{ .Values.workflowEngine.service.targetPort }}
  type: {{ .Values.workflowEngine.service.type }}
