{{- if .Values.workflowEngine.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubiya-runner.serviceAccountName.workflowEngine" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "workflow-engine.labels" . | indent 4 }}
  automountServiceAccountToken: {{ .Values.workflowEngine.serviceAccount.automountServiceAccountToken }}
{{- end }}
