# Cluster wide PVC access role, enabled by default
# !!! TODO: This role must be reviewed + implement user acknowledge from within UI on installation provision for this scope
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kubiya-runner.name" . }}-tool-manager-cluster-pvc-access
  labels:
    {{- include "tool-manager.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["persistentvolumes", "persistentvolumeclaims"]
    verbs: ["create", "get", "list", "delete", "patch", "update"]
