# Cluster wide full access role. Disabled by default, but can be enabled from values.
# User acknowledgement checkbox implemented on UI (on installation provision phase).
{{- if .Values.toolManager.adminClusterRole.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kubiya-runner.name" . }}-tool-manager-fullaccess
  labels:
    {{- include "tool-manager.labels" . | nindent 4 }}
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
{{- end }}
