apiVersion: v1
kind: Service
metadata:
  name: {{ include "neko.fullname" . }}
  labels:
    {{- include "neko.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
    - port: 59000
      targetPort: 59000
      protocol: UDP
      name: udpmux
  selector:
    {{- include "neko.selectorLabels" . | nindent 4 }}
