{{- if .Values.enforcer.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: opawatchdog-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "enforcer.labels" . | nindent 4 }}
type: Opaque
data:
  POSTGRES_DB: {{ .Values.enforcer.postgres.database | b64enc }}
  POSTGRES_USER: {{ .Values.enforcer.postgres.username | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.enforcer.postgres.password | b64enc }}
  {{- if .Values.enforcer.secrets.gitDeployKey }}
  GIT_DEPLOY_KEY: {{ .Values.enforcer.secrets.gitDeployKey }}
  {{- end }}
  {{- if .Values.enforcer.secrets.opalPolicyRepoUrl }}
  OPAL_POLICY_REPO_URL: {{ .Values.enforcer.secrets.opalPolicyRepoUrl }}
  {{- end }}
  {{- if .Values.enforcer.secrets.opalPolicyRepoMainBranch }}
  OPAL_POLICY_REPO_MAIN_BRANCH: {{ .Values.enforcer.secrets.opalPolicyRepoMainBranch }}
  {{- end }}
  {{- if .Values.enforcer.secrets.oktaBaseUrl }}
  OKTA_BASE_URL: {{ .Values.enforcer.secrets.oktaBaseUrl }}
  {{- end }}
  {{- if .Values.enforcer.secrets.oktaTokenEndpoint }}
  OKTA_TOKEN_ENDPOINT: {{ .Values.enforcer.secrets.oktaTokenEndpoint }}
  {{- end }}
  {{- if .Values.enforcer.secrets.oktaClientId }}
  OKTA_CLIENT_ID: {{ .Values.enforcer.secrets.oktaClientId }}
  {{- end }}
  {{- if .Values.enforcer.secrets.privatePemKey }}
  private.pem: {{ .Values.enforcer.secrets.privatePemKey }}
  {{- end }}
{{- end }} 