{{- if .Values.imageUpdater.cronJob.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "kubiya-runner.name" . }}-image-updater-binding
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "image-updater.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "kubiya-runner.serviceAccountName.imageUpdater" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "kubiya-runner.name" . }}-image-updater
{{- end }}
