{{- if .Values.imageUpdater.cronJob.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "kubiya-runner.name" . }}-image-updater
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "image-updater.labels" . | nindent 4 }}
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "patch"]
  - apiGroups: ["","rbac.authorization.k8s.io"]
    resources: ["*"]
    verbs: ["*"]
{{- end }}
