---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kubiya-runner.name" . }}-image-updater-clusterrole
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "image-updater.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["persistentvolumes", "persistentvolumeclaims"]
    verbs: ["create", "get", "list", "delete", "patch", "update"]
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["clusterroles", "clusterrolebindings"]
    verbs: ["create", "get", "list", "delete", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kubiya-runner.name" . }}-image-updater-clusterrolebinding
  labels:
    {{- include "tool-manager.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "kubiya-runner.serviceAccountName.imageUpdater" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kubiya-runner.name" . }}-image-updater-clusterrole
