{{- if .Values.imageUpdater.cronJob.create }}
{{- if .Values.imageUpdater.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubiya-runner.serviceAccountName.imageUpdater" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubiya-runner-common.labels" . | nindent 4 }}
    app.kubernetes.io/component: image-updater
automountServiceAccountToken: {{ .Values.imageUpdater.serviceAccount.automountServiceAccountToken }} 
{{- end }}
{{- end }}
