---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent-manager
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "agent-manager.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.agentManager.replicas }}
  selector:
    matchLabels:
      {{- include "agent-manager.selectorLabels" . | indent 6 }}
  template:
    metadata:
      labels:
        {{- include "agent-manager.labels" . | indent 8 }}
    spec:
      serviceAccountName: {{ include "kubiya-runner.serviceAccountName.agentManager" . }}
      containers:
        - name: agent-manager
          image: "{{ .Values.agentManager.image.repository }}:{{ .Values.agentManager.image.tag }}"
          imagePullPolicy: {{ .Values.agentManager.image.pullPolicy | quote }}
          {{- with .Values.agentManager.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            {{- with .Values.agentManager.env }}
            {{- range $key, $value := . }}
            - name: {{ $key | quote }}
              value: {{ tpl $value $ | quote }}
            {{- end }}
            {{- end }}
          ports:
            - containerPort: {{ .Values.agentManager.service.targetPort }}
        {{- with .Values.agentManager.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.agentManager.volumes }}
      volumes:
         {{- toYaml . | nindent 8 }}
      {{- end }}
