---
apiVersion: v1
kind: Service
metadata:
  name: agent-manager
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "agent-manager.labels" . | indent 4 }}
    {{- if .Values.agentManager.otelCollectorMetricsScrapeAppName }}
    kubiya.io/metrics-name: {{ .Values.agentManager.otelCollectorMetricsScrapeAppName}}
    {{- end }}
spec:
  selector:
    {{- include "agent-manager.selectorLabels" . | indent 4 }}
  ports:
    - name: http
      port: {{ .Values.agentManager.service.port }}
      targetPort: {{ .Values.agentManager.service.targetPort }}
  type: {{ .Values.agentManager.service.serviceType | quote }}
