{{- if .Values.agentManager.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubiya-runner.serviceAccountName.agentManager" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "agent-manager.labels" . | indent 4 }}
  automountServiceAccountToken: {{ .Values.agentManager.serviceAccount.automountServiceAccountToken }}
{{- end }}
