{{- if .Values.daggerChartAddons.roleBinding.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "kubiya-runner.name" . }}-dagger-binding
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dagger-extras.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.dagger.newServiceAccount.name }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "kubiya-runner.name" . }}-dagger
{{- end }}
