# Service discovery of Dagger engine daemonset pods via headless service, used for DNS SRV lookups required for round-robin load balancing.

# Service resource is not available in vendor's dagger subchart, so this additional service allows tool-manager to discover dagger engine pods by service name and do balancing.
# This expected to replace problematic custom .sh + go based implementation in tool-manager with native k8s capabilities for discovery and balancing.
# Also, dagger pods have no ports defined, however it's container's exposed ports are still implicitly exposed as well on pod's IP (if binded to all virtual interfaces).

{{- if .Values.daggerChartAddons.service.create }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubiya-runner.fullname" . }}-dagger-engine
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubiya-runner-common.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    name: {{ include "dagger.fullname" . }}-dagger-engine
  ports:
    - name: dagger
      port: {{ default 8080 .Values.daggerDiscoveryServicePort }}
      targetPort: {{ default 8080 .Values.daggerDiscoveryServicePort }}
      protocol: TCP
{{- end }}
