apiVersion: v2
name: kubiya-runner
description: A Helm chart for Kubiya Runner deployment
type: application
version: 0.5.23
appVersion: "0.5.23"
kubeVersion: ">=1.19.0-0"
home: https://kubiya.ai
icon: https://raw.githubusercontent.com/kubiyabot/helm-charts/main/charts/kubiya-runner/icon.png
sources:
- https://github.com/kubiyabot/helm-charts
keywords:
- kubiya.ai
- runner
maintainers:
- name: Costa
  email: costa@kubiya.ai
- name: Sergey Demyachonok
  email: sergey.demyachonok@kubiya.ai
dependencies:
- name: dagger-helm
  version: "0.2.2"
  repository: "file://../dagger-helm"
  alias: dagger
  condition: dagger.enabled
- name: kube-state-metrics
  version: 5.27.0
  repository: "https://prometheus-community.github.io/helm-charts"
  alias: kubestatemetrics
  condition: kube-state-metrics.enabled
- name: opentelemetry-collector
  alias: otelcollector
  version: 0.109.0
  repository: "https://open-telemetry.github.io/opentelemetry-helm-charts"
  condition: opentelemetry-collector.enabled
- name: prometheus-blackbox-exporter
  alias: blackboxexporter
  version: 8.5.0
  repository: https://prometheus-community.github.io/helm-charts
  condition: blackboxexporter.enabled
