apiVersion: v2
name: kubiya-runner
description: A Helm chart for Kubiya Runner deployment
type: application
version: 0.8.7
appVersion: "0.8.7"
kubeVersion: ">=1.19.0-0" 
home: https://kubiya.ai
icon: https://raw.githubusercontent.com/kubiyabot/helm-charts/main/charts/kubiya-runner/icon.png
sources:
- https://github.com/kubiyabot/helm-charts
keywords:
- kubiya.ai
- runner
maintainers:
- name: Costa
  email: costa@kubiya.ai
- name: Sergey Demyachonok
  email: sergey.demyachonok@kubiya.ai
annotations:
  artifacthub.io/signKey: |
    fingerprint: F6E3E1F5B1B5B5A5C5D5E5F5G5H5I5J5K5L5M5N5
    url: https://kubiya.ai/keys/signing-key.asc
  artifacthub.io/changes: |
    - kind: changed
      description: Updated to chart version 0.8.0 with latest component versions
    - kind: changed  
      description: Updated Agent Manager to v0.4.3
    - kind: changed
      description: Updated Tool Manager to v0.5.4
    - kind: changed
      description: Updated SDK Server to v1.20.0
    - kind: changed
      description: Updated Workflow Engine to v1.46.1
    - kind: changed
      description: Updated Dagger Engine to v0.2.1
    - kind: changed
      description: Updated Dagger Helm dependency to v0.4.1
dependencies:
- name: dagger-helm
  version: "0.4.1"
  repository: "file://../dagger-helm"
  alias: dagger
  condition: dagger.enabled
- name: kube-state-metrics
  version: 5.27.0
  repository: "https://prometheus-community.github.io/helm-charts"
  alias: kubestatemetrics
  condition: kubestatemetrics.enabled
- name: alloy
  version: 0.10.1
  alias: alloy
  repository: https://grafana.github.io/helm-charts
  condition: alloy.enabled
