apiVersion: v2
name: kubiya-runner
description: A Helm chart for deploying the Kubiya operator and related services

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.3

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
# appVersion: "1.0"

dependencies: 
# official command: helm install my-dagger-helm oci://registry.dagger.io/dagger-helm --version 0.13.6
# image: {{ if .Values.engine.image.ref }}{{ .Values.engine.image.ref }}{{ else }}registry.dagger.io/engine:v{{ .Chart.Version }}{{ end }}
# I need to set v0.11.6 as the version for the image and also pass the engine.image.ref registry.dagger.io/engine
- name: dagger-engine
  version: 0.13.6
  repository: https://github.com/dagger/dagger.git
  condition: dagger-engine.enabled
   
