namespace: kubiya
jwt: "bWVnYV9zZWNyZXRfa2V5Cg=="
secondJwt: "bWVnYV9zZWNyZXRfa2V5Cg=="
subject: "jghfjgf"
terminationGracePeriodSeconds: 300
organization: "your_organization_name"
uuid: "unique_identifier"
natsServerUrl: "tls://connect.ngs.global"

kubiyaOperator:
  name: "kubiya-operator"
  replicas: 1
  image:
    repository: ghcr.io/kubiyabot/kubiya-operator
    pullPolicy: Always
    tag: latest
  volumeMounts: 
  - name: runner-secret-volume
    mountPath: "/etc/nats"
    readOnly: true
  volumes:
    - name: runner-secret-volume
      secret:
        secretName: runner-secret # pragma: allowlist secret
        items:
          - key: nats.creds
            path: nats.creds
  ports:
    containerPort: 80

agentManager:
  name: "agent-manager"
  replicas: 2
  image:
    repository: ghcr.io/kubiyabot/agent-manager   
    pullPolicy: Always
    tag: v0.0.3  
  service:
    port: 80
    targetPort: 8080
    serviceType: "ClusterIP"
  volumeMounts:
  - name: creds-volume
    mountPath: "/opt/"
    readOnly: true
  - name: shared-volume
    mountPath: "/tmp/kubiya_shared_tools"
    readOnly: false
  volumes:
    - name: creds-volume
      secret:
        secretName: runner-secret # pragma: allowlist secret
        items:
          - key: nats.creds
            path: nats.creds

kubiyaSuperRole:
  name: "kubiya-super-role"
  
kubiyaSuperRoleBinding:
  name: "kubiya-super-role-binding"

toolManager:
  name: "tool-manager"
  deployedBy: kubiya
  image:
    repository: ghcr.io/kubiyabot/tool-manager
    pullPolicy: Always
    tag: latest
  service:
    port: 80
  containerPort: 3001
  serviceType: "ClusterIP"
  volumes: 
  - name: nats-creds-volume
    secret:
      secretName: nats-creds # pragma: allowlist secret
      items:
        - key: nats.creds
          path: nats.creds
  # Additional volumeMounts on the output Deployment definition.
  volumeMounts: 
  - name: nats-creds-volume
    mountPath: "/opt"

  sdkServer:
    name: "kubiya-sdk-server"
    image:
      repository: ghcr.io/kubiyabot/sdk-py
      pullPolicy: Always
      tag: v0.2.0
    command: 
      - "python"
      - "-m"
      - "kubiya_sdk"
      - "server"
      - "--host"
      - "0.0.0.0"
      - "--port"
      - "8000"
    containerPort: 8000
    defaultMode: 420
 
daggerRole:
  name: "dagger-super-role"

daggerRoleBinding:
  name: "dagger-super-role-binding"

kubiyaSuperAccount:
  name: "kubiya-super-account"

dagger:
  enabled: true
  engine:
    image:
      ref: registry.dagger.io/engine:v0.11.6
    config: |
      debug = true
      insecure-entitlements = ["security.insecure"]
      [registry."ghcr.io"]
        http = true
      [registry."ttl.sh"]
        http = true
      [registry."docker.io"]
        http = true
      [registry."cache-registry-svc.kubiya"]
      [log]
        format = "json"
      
  magicache:
    enabled: false
    ### Create your token via https://docs.dagger.io/manuals/user/cloud-get-started/#step-2-connect-to-dagger-cloud
    #
    # token: YOUR_DAGGER_CLOUD_TOKEN

    ### If secretName is set, a new secret will NOT be created
    #
    # secretName: EXISTING_SECRET_NAME
