{
 "title": "Kubiya Runners Health",
 "description": "Kubiya Runners Health Status",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "organization", "label": "Organization", "query": { "query": "label_values(organization)" } },
   {
    "name": "runner",
    "label": "Runner",
    "query": {
     "query": "label_values(runner{organization=\"$organization\"})"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(namespace{organization=\"$organization\", runner=\"$runner\"})"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Components Availability",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{namespace=~\"$namespace\", runner=\"$runner\", organization=\"$organization\", kubiya_type=\"customers-runners\"}",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "probe_duration_seconds{namespace=~\"$namespace\", runner=\"$runner\", organization=\"$organization\", kubiya_type=\"customers-runners\"}",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "5m Availability",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg_over_time(probe_success{namespace=~\"$namespace\", runner=\"$runner\", organization=\"$organization\", kubiya_type=\"customers-runners\"}[5m])",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "Components Status",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by (pod, container) (kube_pod_container_status_running{namespace=~\"$namespace\", runner=\"$runner\", organization=\"$organization\", kubiya_type=\"customers-runners\"}) * 100",
     "legendFormat": "Running"
    },
    {
     "expr": "sum by (pod, container) (kube_pod_container_status_waiting{namespace=~\"$namespace\", runner=\"$runner\", organization=\"$organization\", kubiya_type=\"customers-runners\"}) * 100",
     "legendFormat": "Waiting"
    },
    {
     "expr": "sum by (pod, container) (kube_pod_container_status_terminated{namespace=~\"$namespace\", runner=\"$runner\", organization=\"$organization\", kubiya_type=\"customers-runners\"}) * 100",
     "legendFormat": "Terminated"
    },
    {
     "expr": "kube_pod_container_status_restarts_total{namespace=~\"$namespace\", runner=\"$runner\", organization=\"$organization\", kubiya_type=\"customers-runners\"}",
     "legendFormat": "Restarts"
    }
   ]
  },
  {
   "title": "Components Versions",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "kube_pod_container_info{namespace=~\"$namespace\", runner=\"$runner\", organization=\"$organization\", kubiya_type=\"customers-runners\"}",
     "legendFormat": "{{container}}"
    },
    {
     "expr": "kube_pod_labels{namespace=~\"$namespace\", runner=\"$runner\", organization=\"$organization\", kubiya_type=\"customers-runners\"}"
    }
   ]
  }
 ]
}