image:
  repository: ghcr.io/m1k1o/neko/firefox
  tag: 3.0.9  # latest stable compatible with Stunner
  pullPolicy: IfNotPresent

turn:
  frontendUrl: "turn:x.x.x.x:3478"
  backendUrl: "turn:udp-gateway.stunner.svc.cluster.local:3478"
  # If secretName is set, username and credential are looked up from the secret.
  # Otherwise, they are taken from the values below.
  # username: "<example username>"
  # credential: "<example password>"
  secretName: "neko-secrets"
  usernameKey: TURN_USERNAME
  credentialKey: TURN_PASSWORD

auth:
  # If secretName is set, adminPass and userPass are looked up from the secret.
  # Otherwise, they are taken from the values below.
  # adminPass: "<example password>"
  # userPass: "<example password>"
  secretName: "neko-secrets"
  adminPassKey: NEKO_PASSWORD_ADMIN
  userPassKey: NEKO_PASSWORD

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

# Ingress Controller (nginx only for now)
ingress:
  enabled: true
  host: neko.kubiya.ai
  # User external or internal ingress class for public/internal access modes
  className: external-nginx
  # Compatibility fix: choose between ingress class via spec (newer k8s) or via annotation (legacy/nginx specific)
  useIngressClassName: false
  tls:
    enabled: true
    clusterIssuer: letsencrypt-prod

serviceAccount:
  create: true
  annotations: {}
  name: ""

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi

shmSize: 2Gi

pdb:
  enabled: false
  minAvailable: 1
