apiVersion: apps/v1
kind: Deployment
metadata:
  name: tool-manager
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tool-manager.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.toolManager.replicas }}
  selector:
    matchLabels:
      {{- include "tool-manager.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- with .Values.toolManager.extraPodsAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "tool-manager.labels" . | nindent 8 }}
    spec:
      {{- with .Values.toolManager.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.toolManager.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "kubiya-runner.serviceAccountName.toolManager" . }}
      containers:
        - name: tool-manager
          image: "{{ .Values.toolManager.image.repository }}:{{ .Values.toolManager.image.tag }}"
          imagePullPolicy: {{ .Values.toolManager.image.pullPolicy | quote }}
          {{- with .Values.toolManager.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          command: {{ .Values.toolManager.command | toYaml | nindent 10 }}
          env:
            {{- with .Values.toolManager.env }}
            {{- range $key, $value := . }}
            - name: {{ $key | quote }}
              value: {{ tpl $value $ | quote }}
            {{- end }}
            {{- end }}
          ports:
            - containerPort: {{ .Values.toolManager.containerPort }}
          {{- with .Values.toolManager.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if .Values.toolManager.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.toolManager.livenessProbe.httpGet.path }}
              port: {{ .Values.toolManager.service.targetPort }}
            initialDelaySeconds: {{ .Values.toolManager.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.toolManager.livenessProbe.periodSeconds }}
          {{- end }}

        - name: kubiya-sdk-server
          image: "{{ .Values.toolManager.sdkServer.image.repository }}:{{ .Values.toolManager.sdkServer.image.tag }}"
          imagePullPolicy: {{ .Values.toolManager.sdkServer.image.pullPolicy | quote }}
          {{- with .Values.toolManager.sdkServer.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          command: {{ .Values.toolManager.sdkServer.command | toYaml | nindent 10 }}
          env:
            {{- with .Values.toolManager.sdkServer.env }}
            {{- range $key, $value := . }}
            - name: {{ $key | quote }}
              value: {{ tpl $value $ | quote }}
            {{- end }}
            {{- end }}
          ports:
            - containerPort: {{ .Values.toolManager.sdkServer.containerPort }}
          {{- with .Values.toolManager.sdkServer.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if .Values.toolManager.sdkServer.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.toolManager.sdkServer.livenessProbe.httpGet.path }}
              port: {{ .Values.toolManager.sdkServer.containerPort }}
            initialDelaySeconds: {{ .Values.toolManager.sdkServer.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.toolManager.sdkServer.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.toolManager.sdkServer.livenessProbe.timeoutSeconds }}
          {{- end }}

        - name: workflow-engine
          image: "{{ .Values.toolManager.workflowEngine.image.repository }}:{{ .Values.toolManager.workflowEngine.image.tag }}"
          imagePullPolicy: {{ .Values.toolManager.workflowEngine.image.pullPolicy | quote }}
          {{- with .Values.toolManager.workflowEngine.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.toolManager.workflowEngine.command }}
          command: {{ toYaml . | nindent 10 }}
          {{- end }}
          env:
            {{- with .Values.toolManager.workflowEngine.env }}
            {{- range $key, $value := . }}
            - name: {{ $key | quote }}
              value: {{ tpl $value $ | quote }}
            {{- end }}
            {{- end }}
          ports:
            - containerPort: {{ .Values.toolManager.workflowEngine.ports.containerPort }}
          {{- with .Values.toolManager.workflowEngine.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if .Values.toolManager.workflowEngine.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.toolManager.workflowEngine.livenessProbe.httpGet.path }}
              port: {{ .Values.toolManager.workflowEngine.containerPort }}
          {{- end }}
      {{- with .Values.toolManager.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
