{{- if .Values.toolManager.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubiya-runner.serviceAccountName.toolManager" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tool-manager.labels" . | nindent 4 }}
  automountServiceAccountToken: {{ .Values.toolManager.serviceAccount.automountServiceAccountToken }} 
{{- end }}
