
apiVersion: v1
kind: Service
metadata:
  name: workflow-engine-svc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tool-manager.labels" . | nindent 4 }}
spec:
  type: {{ .Values.toolManager.workflowEngine.service.type }}
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "tool-manager.selectorLabels" . | nindent 4 }}
