
apiVersion: v1
kind: Service
metadata:
  name: wf-engine-svc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tool-manager.labels" . | nindent 4 }}
    {{- if .Values.toolManager.workflowEngine.otelCollectorMetricsScrapeAppName }}
    kubiya.io/metrics-name: {{ .Values.toolManager.workflowEngine.otelCollectorMetricsScrapeAppName }}
    {{- end }}
spec:
  type: {{ .Values.toolManager.workflowEngine.service.type }}
  ports:
    - port: {{ .Values.toolManager.workflowEngine.service.port }}
      targetPort: {{ .Values.toolManager.workflowEngine.ports.containerPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "tool-manager.selectorLabels" . | nindent 4 }}
