apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.agentManager.name | quote }}
  namespace: {{ .Values.namespace | quote }}
spec:
  selector:
    app: {{ .Values.agentManager.name | quote }}
  ports:
    - name: http
      port: {{ .Values.agentManager.service.port }}
      targetPort: {{ .Values.agentManager.service.targetPort }}
  type: {{ .Values.agentManager.service.serviceType | quote }}
