---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubiya-runner.name" . }}-agent-manager
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubiya-runner-agent-manager.labels" . | indent 4 }}
spec:
  selector:
    {{- include "kubiya-runner-agent-manager.selectorLabels" . | indent 4 }}
  ports:
    - name: http
      port: {{ .Values.agentManager.service.port }}
      targetPort: {{ .Values.agentManager.service.targetPort }}
  type: {{ .Values.agentManager.service.serviceType | quote }}
