{{- if .Values.agentManager.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubiya-runner.serviceAccountName.agentManager" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubiya-runner-common.labels" . | nindent 4 }}
    app.kubernetes.io/component: agent-manager
automountServiceAccountToken: {{ .Values.agentManager.serviceAccount.automountServiceAccountToken }} 
{{- end }}
