apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Values.daggerDaemonset.name | quote }}
  namespace: {{ .Values.daggerDaemonset.namespace | quote }}
  labels:
    helm.sh/chart: dagger-helm-{{ .Values.daggerDaemonset.helmChartVersion }}
    app.kubernetes.io/name: dagger-helm
    app.kubernetes.io/instance: dagger
    app.kubernetes.io/version: {{ .Values.daggerDaemonset.AppVersion | quote }}
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: dagger-helm
spec:
  selector:
    matchLabels:
      name: {{ .Values.daggerDaemonset.name | quote }}
  template:
    metadata:
      labels:
        name: {{ .Values.daggerDaemonset.name | quote }}
    spec:
      securityContext:
        {{- toYaml .Values.daggerDaemonset.SecurityContext | nindent 8 }}
      serviceAccountName: default
      containers:
        - name: dagger-engine
          image: "{{ .Values.daggerDaemonset.image.repository }}:{{ .Values.daggerDaemonset.image.tag }}"
          imagePullPolicy: {{ .Values.daggerDaemonset.image.pullPolicy | quote }}
          args:
            {{- toYaml .Values.daggerDaemonset.args | nindent 12 }}
          securityContext:
            privileged: {{ .Values.daggerDaemonset.privileged}}
            capabilities:
              add:
                {{- toYaml .Values.daggerDaemonset.capabilities.add | nindent 16 }}
          resources:
            limits: {}
            requests: {}
          readinessProbe:
            {{- toYaml .Values.daggerDaemonset.readinessProbe | nindent 12 }}
          volumeMounts:
            {{- if .Values.daggerDaemonset.additionalVolumeMounts }}
            {{- toYaml .Values.daggerDaemonset.additionalVolumeMounts | nindent 12}}  
            {{- end }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      volumes:
        {{- if $.Values.daggerDaemonset.additionalVolumes }}
        {{- toYaml $.Values.daggerDaemonset.additionalVolumes | nindent 8}}  
        {{- end }}