---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.kubiyaSuperRoleBinding.name | quote }}
  namespace: {{ .Values.namespace | quote }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.kubiyaSuperAccount.name | quote }}
    namespace: {{ .Values.namespace  }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.kubiyaSuperRole.name | quote }}
