---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.daggerRole.name | quote }}
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: [ "" ]
    resources: ["*"]
    verbs: [ "*" ]
