# Operator ServiceAccount
{{- if .Values.kubiyaOperator.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubiya-runner.serviceAccountName.operator" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubiya-runner-common.labels" . | nindent 4 }}
    app.kubernetes.io/component: operator
automountServiceAccountToken: {{ .Values.kubiyaOperator.serviceAccount.automountServiceAccountToken }}
{{- end }}
---
# Tool Manager ServiceAccount
{{- if .Values.toolManager.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubiya-runner.serviceAccountName.toolManager" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubiya-runner-common.labels" . | nindent 4 }}
    app.kubernetes.io/component: tool-manager
automountServiceAccountToken: {{ .Values.toolManager.serviceAccount.automountServiceAccountToken }}
{{- end }}
---
# Agent Manager ServiceAccount
{{- if .Values.agentManager.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubiya-runner.serviceAccountName.agentManager" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubiya-runner-common.labels" . | nindent 4 }}
    app.kubernetes.io/component: agent-manager
automountServiceAccountToken: {{ .Values.agentManager.serviceAccount.automountServiceAccountToken }}
{{- end }}
---
# Image Updater ServiceAccount
{{- if .Values.imageUpdater.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubiya-runner.serviceAccountName.imageUpdater" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubiya-runner-common.labels" . | nindent 4 }}
    app.kubernetes.io/component: image-updater
automountServiceAccountToken: {{ .Values.imageUpdater.serviceAccount.automountServiceAccountToken }}
{{- end }}
---
