{{- if .Values.nats.jwt -}}
apiVersion: v1
kind: Secret
metadata:
  name: kubiya-runner-nats-creds-runner
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubiya-runner-common.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
type: Opaque
data:
  nats.creds: {{ .Values.nats.jwt | quote }}
{{- end }}
---
{{- if .Values.secondJwt -}}
apiVersion: v1
kind: Secret
metadata:
  name: kubiya-runner-nats-creds-customer
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubiya-runner-common.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
type: Opaque
data:
  nats.creds: {{ .Values.secondJwt | quote }}
{{- end }}
---
{{- if and .Values.registryTls.crt .Values.registryTls.key -}}
apiVersion: v1
kind: Secret
metadata:
  name: kubiya-runner-registry-tls-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubiya-runner-common.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.registryTls.crt | quote }}
  tls.key: {{ .Values.registryTls.key | quote }}
{{- end }}
