---
apiVersion: v1
kind: Service
metadata:
  name: tool-manager
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tool-manager.labels" . | indent 4 }}
spec:
  selector:
    {{- include "tool-manager.selectorLabels" . | indent 4 }}
  ports:
    - name: http
      port: {{ .Values.tool.service.port }}
      targetPort: {{ .Values.tool.service.targetPort }}
  type: {{ .Values.tool.service.serviceType | quote }}
