{{- if .Values.toolManager.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubiya-runner.serviceAccountName.toolManager" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubiya-runner-common.labels" . | nindent 4 }}
    app.kubernetes.io/component: tool-manager
automountServiceAccountToken: {{ .Values.toolManager.serviceAccount.automountServiceAccountToken }} 
{{- end }}

