# Enabled by default, role with permisson set enough for tool-manager operation within it's release namespace scope.
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "kubiya-runner.name" . }}-tool-manager-namespace-scope
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tool-manager.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["pods", "secrets", "deployments", "pvcs", "services"]
    verbs: ["get", "list", "create"]
  - apiGroups: ["apps"]
    resources: ["pods", "secrets", "deployments"]
    verbs: ["get", "list", "create"]
