{
 "title": "Customer Runners / ALL Runners Cumulative Health",
 "description": "Shows all Runners deployments health state based on calculated single cumulative health score. \n- Cumulative score is unweighted - all health signals are counted equal.\n- Current state (last 5m) - shown for each runner as single block on Stat chart. \n- Last x hours health dynamics shown below on State Timeline chart.\n- Both charts are interactive - clicking on each block will open new tab with detailed health signals breakdown dashboard for particular runner.",
 "tags": [
  "customer_runner_metrics",
  "prometheus",
  "customer_runner",
  "managed_runner",
  "agent_manager",
  "metrics",
  "tool_manager",
  "global_runner_health",
  "global_health_score"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Runners Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "All Runners Health State (Last 5m)",
   "type": "stat",
   "description": "The number on each Stat panel block shows Runner's Cumulative CURRENT (last 5m) health score, on 0 to 100 scale, while background on each block shows score changes for selected dashboard’s timeframe.",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  ((sum by (organization, runner) ( rate(response_status{status=~\"2..\", namespace=~\"$namespace|.*\", organization!=\"\", app=\"tool-manager\", kubiya_type=\"customers-runners\"}[5m])) / sum by (organization, runner) (rate(http_requests_total{namespace=~\"$namespace|.*\", organization!=\"\", app=\"tool-manager\", kubiya_type=\"customers-runners\"}[5m])) ) * 100) \n+ \n((sum by (organization, runner) ( rate(agent_manager_http_requests_total{status=~\"2..\", namespace=~\"$namespace|.*\", organization!=\"\", app=\"agent-manager\", kubiya_type=\"customers-runners\"}[5m]) ) / sum by (organization, runner) ( rate(agent_manager_http_requests_total{namespace=~\"$namespace|.*\", organization!=\"\", app=\"agent-manager\", kubiya_type=\"customers-runners\"}[5m]) )) * 100)\n+\n(( sum by (organization, runner) ( avg_over_time( kube_pod_status_ready{ namespace=~\"$namespace|.*\", organization!=\"\", kubiya_type=\"customers-runners\", condition=\"true\" }[5m] ) * on (pod) group_left(label_app_kubernetes_io_kubiya_runner_component) kube_pod_labels{ namespace=~\"$namespace|.*\", organization!=\"\", kubiya_type=\"customers-runners\", label_job_name=\"\" } and on (pod) kube_pod_labels{label_app_kubernetes_io_kubiya_runner_component!=\"\"} ) / count by (organization, runner) ( kube_pod_labels{ namespace=~\"$namespace|.*\", organization!=\"\", kubiya_type=\"customers-runners\", label_app_kubernetes_io_kubiya_runner_component!=\"\", label_job_name=\"\" })) * 100)\n+\n(( 1 - clamp_max( sum by (organization, runner)( rate(kube_pod_container_status_restarts_total{ namespace=~\"$namespace|.*\", organization!=\"\", kubiya_type=\"customers-runners\", label_job_name=\"\" }[5m]) * on (pod) group_left(label_app_kubernetes_io_kubiya_runner_component) kube_pod_labels{ namespace=~\"$namespace|.*\", organization!=\"\", kubiya_type=\"customers-runners\", label_job_name=\"\", label_app_kubernetes_io_kubiya_runner_component!=\"\" } ) * 300 / 1.0 , 1)) * 100)\n+\n(avg by (organization, runner) ( avg_over_time(probe_success{ namespace=~\"$namespace|.*\", organization!=\"\", kubiya_type=\"customers-runners\", exporter=\"blackbox-exporter\"}[5m]) ) * 100)\n) /5",
     "legendFormat": "{{organization}}/{{runner}}"
    },
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "All Runners Health Timeline (per 5m)",
   "type": "status-history",
   "description": "Shows Cumulative Runner Health for Selected Timeline Period (per each 5m(",
   "gridPos": { "h": 28, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(\n  ((sum by (organization, runner) ( rate(response_status{status=~\"2..\", namespace=~\"$namespace|.*\", organization!=\"\", app=\"tool-manager\", kubiya_type=\"customers-runners\"}[5m])) / sum by (organization, runner) (rate(http_requests_total{namespace=~\"$namespace|.*\", organization!=\"\", app=\"tool-manager\", kubiya_type=\"customers-runners\"}[5m])) ) * 100)\n+ \n((sum by (organization, runner) ( rate(agent_manager_http_requests_total{status=~\"2..\", namespace=~\"$namespace|.*\", organization!=\"\", app=\"agent-manager\", kubiya_type=\"customers-runners\"}[5m]) ) / sum by (organization, runner) ( rate(agent_manager_http_requests_total{namespace=~\"$namespace|.*\", organization!=\"\", app=\"agent-manager\", kubiya_type=\"customers-runners\"}[5m]) )) * 100)\n+\n(( sum by (organization, runner) ( avg_over_time( kube_pod_status_ready{ namespace=~\"$namespace|.*\", organization!=\"\", kubiya_type=\"customers-runners\", condition=\"true\" }[5m] ) * on (pod) group_left(label_app_kubernetes_io_kubiya_runner_component) kube_pod_labels{ namespace=~\"$namespace|.*\", organization!=\"\", kubiya_type=\"customers-runners\", label_job_name=\"\" } and on (pod) kube_pod_labels{label_app_kubernetes_io_kubiya_runner_component!=\"\"} ) / count by (organization, runner) ( kube_pod_labels{ namespace=~\"$namespace|.*\", organization!=\"\", kubiya_type=\"customers-runners\", label_app_kubernetes_io_kubiya_runner_component!=\"\", label_job_name=\"\" })) * 100)\n+\n(( 1 - clamp_max( sum by (organization, runner)( rate(kube_pod_container_status_restarts_total{ namespace=~\"$namespace|.*\", organization!=\"\", kubiya_type=\"customers-runners\", label_job_name=\"\" }[5m]) * on (pod) group_left(label_app_kubernetes_io_kubiya_runner_component) kube_pod_labels{ namespace=~\"$namespace|.*\", organization!=\"\", kubiya_type=\"customers-runners\", label_job_name=\"\", label_app_kubernetes_io_kubiya_runner_component!=\"\" } ) * 300 / 1.0 , 1)) * 100)\n+\n(avg by (organization, runner) ( avg_over_time(probe_success{ namespace=~\"$namespace|.*\", organization!=\"\", kubiya_type=\"customers-runners\", exporter=\"blackbox-exporter\"}[5m]) ) * 100)\n) /5",
     "legendFormat": "{{organization}}/{{runner}}"
    }
   ]
  },
  {
   "title": "Versions Installed",
   "type": "table",
   "description": "Shows ALL versions of kubiya-runner helm chart which were installed within selected time frame",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "kube_pod_labels{namespace=~\"$namespace|.*\", organization!=\"\", label_helm_sh_chart=~\"kubiya-runner.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Debug Detailed Health Signals per Runner",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 },
   "collapsed": true,
   "panels": [
    {
     "title": "HTTP Requests Success Rate - Tool Manager",
     "type": "state-timeline",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 63 },
     "targets": [
      {
       "expr": "(\n   sum by (organization, runner) (\n      rate(response_status{status=~\"2..\", namespace=~\"$namespace|.*\", organization!=\"\", app=\"tool-manager\", kubiya_type=\"customers-runners\"}[5m])\n   )\n   /\n   sum by (organization, runner) (\n      rate(http_requests_total{namespace=~\"$namespace|.*\", organization!=\"\", app=\"tool-manager\", kubiya_type=\"customers-runners\"}[5m])\n   )\n) * 100",
       "legendFormat": "{{organization}} / {{runner}}"
      }
     ]
    },
    {
     "title": "Container Restarts (Per Minute) Health Score",
     "type": "state-timeline",
     "description": "The container restart health signal is designed to show how often containers are restarting. Instead of just showing a raw restart count, we normalize the value to a 0-100 health scale, so it is easier to compare with other health metrics.\n* 0 restarts per 5 mins → 100% healthy\n* 1 restart per 5 mins → 0% healthy",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(\n  1 - clamp_max(\n    sum by (organization, runner)(\n      rate(kube_pod_container_status_restarts_total{\n        namespace=~\"$namespace|.*\",\n        organization!=\"\",\n        kubiya_type=\"customers-runners\",\n        label_job_name=\"\"\n      }[5m])\n      * on (pod) group_left(label_app_kubernetes_io_kubiya_runner_component)\n      kube_pod_labels{\n        namespace=~\"$namespace|.*\",\n        organization!=\"\",\n        kubiya_type=\"customers-runners\",\n        label_job_name=\"\",\n        label_app_kubernetes_io_kubiya_runner_component!=\"\"\n      }\n    )\n    * 300   # 300 seconds (5 minutes)\n    / 1.0   # 1 restart per 5 min considered problematic\n  , 1)\n) * 100",
       "legendFormat": "{{organization}} / {{runner}}"
      }
     ]
    },
    {
     "title": "Components Pods Ready",
     "type": "state-timeline",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(\n  sum by (organization, runner) (\n    avg_over_time(\n      kube_pod_status_ready{\n        namespace=~\"$namespace|.*\",\n        organization!=\"\",\n        kubiya_type=\"customers-runners\",\n        condition=\"true\"\n      }[5m]\n    )\n    * on (pod) group_left(label_app_kubernetes_io_kubiya_runner_component)\n    kube_pod_labels{\n      namespace=~\"$namespace|.*\",\n      organization!=\"\",\n      kubiya_type=\"customers-runners\",\n      label_job_name=\"\"\n    }\n    and on (pod) kube_pod_labels{label_app_kubernetes_io_kubiya_runner_component!=\"\"}\n  )\n  /\n  count by (organization, runner) (\n    kube_pod_labels{\n      namespace=~\"$namespace|.*\",\n      organization!=\"\",\n      kubiya_type=\"customers-runners\",\n      label_app_kubernetes_io_kubiya_runner_component!=\"\",\n      label_job_name=\"\"\n    }\n  )\n) * 100",
       "legendFormat": "{{organization}} / {{runner}}"
      }
     ]
    },
    {
     "title": "HTTP Requests Success Rate - Agent Manager",
     "type": "state-timeline",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 76 },
     "targets": [
      {
       "expr": "(\n   sum by (organization, runner, namespace) (\n      rate(agent_manager_http_requests_total{status=~\"2..\", namespace=~\"$namespace|.*\", organization!=\"\", app=\"agent-manager\", kubiya_type=\"customers-runners\"}[5m])\n   )\n   /\n   sum by (organization, runner, namespace) (\n      rate(agent_manager_http_requests_total{namespace=~\"$namespace|.*\", organization!=\"\", app=\"agent-manager\", kubiya_type=\"customers-runners\"}[5m])\n   )\n) * 100",
       "legendFormat": "{{organization}} / {{runner}}"
      }
     ]
    },
    {
     "title": "Services Health Endpoint Probe [per 5m]",
     "type": "state-timeline",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 89 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "avg by (organization, runner) (\n  avg_over_time(probe_success{ namespace=~\"$namespace|.*\", organization!=\"\", kubiya_type=\"customers-runners\", exporter=\"blackbox-exporter\"}[5m])\n) * 100",
       "legendFormat": "{{organization}} / {{runner}}"
      }
     ]
    }
   ]
  }
 ]
}