{
 "title": "Customer Runners / Blackbox Exporter",
 "description": "Blackbox exporter HTTP prober dashboard",
 "tags": [
  "customer_runner_metrics",
  "blackbox",
  "prometheus"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Target",
    "query": "label_values(probe_success, job)"
   },
   {
    "name": "organization",
    "query": {
     "query": "label_values(up{kubiya_type=\"customers-runners\"},organization)"
    }
   },
   {
    "name": "runner",
    "query": {
     "query": "label_values(up{kubiya_type=\"customers-runners\", organization=~\"$organization\"},runner)"
    }
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(up{kubiya_type=\"customers-runners\", organization=~\"$organization\", runner=~\"$runner\"},namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "HTTP Probe Overview",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "probe_success{job=~\"$job\", organization=~\"$organization\", runner=~\"$runner\", namespace=~\"$namespace\"}"
    },
    {
     "expr": "probe_http_ssl{job=~\"$job\", organization=~\"$organization\", runner=~\"$runner\", namespace=~\"$namespace\"} > 0"
    },
    {
     "expr": "(probe_ssl_earliest_cert_expiry{job=~\"$job\", organization=~\"$organization\", runner=~\"$runner\", namespace=~\"$namespace\"} - time()) / 3600 / 24"
    },
    {
     "expr": "probe_http_status_code{job=~\"$job\", organization=~\"$organization\", runner=~\"$runner\", namespace=~\"$namespace\"} > 0"
    },
    {
     "expr": "avg_over_time(probe_duration_seconds{job=~\"$job\", organization=~\"$organization\", runner=~\"$runner\", namespace=~\"$namespace\"}[1m])"
    },
    {
     "expr": "probe_tls_version_info{job=~\"$job\", organization=~\"$organization\", runner=~\"$runner\", namespace=~\"$namespace\"}"
    },
    {
     "expr": "avg_over_time(probe_dns_lookup_time_seconds{job=~\"$job\", organization=~\"$organization\", runner=~\"$runner\", namespace=~\"$namespace\"}[1m])"
    }
   ]
  },
  {
   "title": "HTTP Probe Duration",
   "type": "timeseries",
   "description": "Returns how long the probe took to complete in seconds",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(probe_http_duration_seconds{job=~\"$job\", organization=~\"$organization\", runner=~\"$runner\", namespace=~\"$namespace\"}) by (job)",
     "legendFormat": "{{ runner }}"
    }
   ]
  },
  {
   "title": "$job",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "repeat": "job",
   "targets": [
    {}
   ]
  },
  {
   "title": "HTTP Probe Phases Duration",
   "type": "timeseries",
   "description": "Duration of http request by phase, summed over all redirects",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "probe_http_duration_seconds{job=~\"$job\", organization=~\"$organization\", runner=~\"$runner\", namespace=~\"$namespace\"}",
     "legendFormat": "{{ phase }}"
    }
   ]
  }
 ]
}