name: Helm Lint

on:
  push:
    paths:
    - 'charts/**'
  pull_request:
    paths:
    - 'charts/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        version: v3.12.3

    - name: Run helm lint
      run: |
        helm lint charts/kubiya-runner/ \
          --strict \
          --skip-tests

    - name: Run helm template
      run: |
        helm template test charts/kubiya-runner/ \
          --debug \
          --skip-tests
