name: Helm Charts CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  helm-ci:
    runs-on: ubuntu-22.04  # Use a pinned runner version to avoid mutability issues
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4  # Use latest stable major version

      # Use a predefined Helm setup action
      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.3  # Pin a specific Helm version for reproducibility

      # Cache Helm dependencies to speed up repeated runs
      - name: Cache Helm Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/helm
          key: helm-${{ runner.os }}-${{ hashFiles('**/Chart.yaml') }}
          restore-keys: |
            helm-${{ runner.os }}-

      # Install dependencies only if not cached
      - name: Install Dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y yamllint
          helm plugin install https://github.com/quintush/helm-unittest --version v0.2.8

      # Package local charts to handle intra-repo dependencies
      - name: Package Local Charts
        run: |
          mkdir -p packaged
          for chart in charts/*; do
            helm package "$chart" --destination packaged
          done

      # Create a local Helm repo from packaged charts
      - name: Set Up Local Helm Repo
        run: |
          helm repo index packaged --url file://$(pwd)/packaged
          helm repo add local-charts file://$(pwd)/packaged
          helm repo update

      # Lint Helm charts with resolved dependencies
      - name: Lint Helm Charts
        run: |
          for chart in charts/*; do
            helm dep up "$chart"
            helm lint "$chart"
          done

      # Run Helm unit tests if defined
      - name: Run Helm Unit Tests
        run: |
          for chart in charts/*; do
            helm unittest "$chart" || echo "No tests defined for $chart"
          done

      # Final build and packaging
      - name: Build and Package Helm Charts
        run: |
          mkdir -p packaged-final
          for chart in charts/*; do
            helm package "$chart" --destination packaged-final
          done

      # Upload packaged charts as artifacts
      - name: Upload Packaged Charts
        uses: actions/upload-artifact@v3
        with:
          name: helm-packaged-charts
          path: packaged-final/
