name: Helm Charts CI

on:
  push:
    branches:
      - main
      - dev
      - tmp_alloy # TODO: temporary including branch for CI refactor debug
  pull_request:
    branches:
      - main
      - dev

jobs:
  helm-ci:
    runs-on: ubuntu-22.04  # Use a pinned runner version to avoid mutability issues
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4  # Use latest stable major version

      # Set up Helm
      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.3  # Pin a specific Helm version for reproducibility

      # Cache Helm dependencies to speed up repeated runs 
      - name: Cache Helm Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/helm
          key: helm-${{ runner.os }}-${{ hashFiles('**/Chart.yaml') }}
          restore-keys: |
            helm-${{ runner.os }}-

      # Install dependencies (yamllint, helm-unittest)
      - name: Install Dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y yamllint
          helm plugin install https://github.com/quintush/helm-unittest --version v0.2.8

      # Step 1: Update Dependencies Before Packaging
      - name: Update Helm Dependencies
        run: |
          for chart in charts/dagger-helm charts/kubiya-runner; do
            if [ -f "$chart/Chart.yaml" ]; then
              echo "Updating dependencies for $chart..."
              helm dep update "$chart"
            fi
          done

      # Step 2: Hardcoded Order for Intra-Repo Chart Packaging
      - name: Package Local Charts
        run: |
          mkdir -p packaged
          
          # Ensure dagger-helm is packaged first
          if [ -d "charts/dagger-helm" ]; then
            echo "Packaging dagger-helm..."
            helm package charts/dagger-helm --destination packaged
          fi
          
          # Ensure kubiya-runner is packaged after dagger-helm
          if [ -d "charts/kubiya-runner" ]; then
            echo "Packaging kubiya-runner..."
            helm package charts/kubiya-runner --destination packaged
          fi

      # Step 3: Create Local Helm Repo
      - name: Create Local Helm Repo
        run: |
          helm repo index packaged --url file://$(pwd)/packaged
          helm repo add local-charts file://$(pwd)/packaged
          helm repo update

      # Step 4: Lint Helm Charts
      - name: Lint Helm Charts
        run: |
          for chart in charts/dagger-helm charts/kubiya-runner; do
            if [ -f "$chart/Chart.yaml" ]; then
              helm lint "$chart"
            fi
          done

      # Step 5: Run Helm Unit Tests
      - name: Run Helm Unit Tests
        run: |
          for chart in charts/dagger-helm charts/kubiya-runner; do
            if [ -f "$chart/Chart.yaml" ]; then
              helm unittest "$chart" || echo "No tests defined for $chart"
            fi
          done

      # Step 6: Final Build and Packaging
      - name: Build and Package Helm Charts
        run: |
          mkdir -p packaged-final
          
          # Ensure dagger-helm is packaged first
          if [ -d "charts/dagger-helm" ]; then
            echo "Packaging final version of dagger-helm..."
            helm package charts/dagger-helm --destination packaged-final
          fi
          
          # Ensure kubiya-runner is packaged after dagger-helm
          if [ -d "charts/kubiya-runner" ]; then
            echo "Packaging final version of kubiya-runner..."
            helm package charts/kubiya-runner --destination packaged-final
          fi

      # Step 7: Upload Packaged Charts as Artifacts
      - name: Upload Packaged Charts
        uses: actions/upload-artifact@v3
        with:
          name: helm-packaged-charts
          path: packaged-final/
