name: Helm Lint

on:
  push:
    paths:
    - 'charts/**'
  pull_request:
    paths:
    - 'charts/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        version: v3.12.3

    - name: Add Helm repositories and update dependencies
      run: |
        helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
        helm repo add open-telemetry https://open-telemetry.github.io/opentelemetry-helm-charts
        helm repo update
          

    - name: Update Helm dependencies
      run: |
        cd charts/kubiya-runner
        # Download and untar dependencies
        helm dependency update
        cd charts
        # Untar all .tgz files
        for f in *.tgz; do
        tar xzf "$f"
        done
        ls -la 

    - name: Run helm lint
      run: |
        helm lint charts/kubiya-runner/ \
          --strict \
          --values charts/kubiya-runner/values.yaml
        #   --with-subcharts

    - name: Run helm template
      run: |
        helm template test charts/kubiya-runner/ \
          --debug \
          --values charts/kubiya-runner/values.yaml
